name: formulario_movil
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-176.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  flutter_lints: ^4.0.0
  url_launcher: ^6.2.4
  sqflite: ^2.3.3+1
  path: ^1.8.0
  google_maps_flutter: ^2.7.0
  dark_light_button: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - lib/imagenes/